version: "2"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: images
      POSTGRES_PASSWORD: images_go
      POSTGRES_DB: imagesapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  images-back:
    image: images-back
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://images:images_go@postgres/imagesapp?sslmode=disable
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
